# Generated by Django 5.2.13 on 2026-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="version",
            field=models.IntegerField(default=0),
        ),
    ]
