# Generated by Django 5.2.13 on 2026-04-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_price",
            new_name="order_price",
        ),
    ]
